import { execFileSync } from "node:child_process";
import { readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { marked } from "marked";

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const GENERATED_PREFIX = "<!-- Generated by scripts/generate-docs.mjs from ";
const DOCUMENT_EXTENSIONS = new Set([".md", ".mdx", ".txt", ".rst", ".adoc"]);
const FORMAT_AWARE_RENDERER_REQUIRED = new Set([".mdx", ".rst", ".adoc"]);
const EXTENSIONLESS_DOCUMENT_NAMES = new Set([
  "authors",
  "changelog",
  "code_of_conduct",
  "contributing",
  "license",
  "licence",
  "notice",
  "readme",
  "security",
]);
const EXCLUDED_PATH_PARTS = new Set([
  ".next",
  ".vercel",
  "build",
  "coverage",
  "dist",
  "node_modules",
  "out",
  "third_party",
  "third-party",
  "vendor",
]);

marked.use({ gfm: true, breaks: true });

function escapeHtml(value) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function repositoryFiles() {
  const output = execFileSync("git", ["ls-files", "-z", "--cached"], {
    cwd: REPO_ROOT,
    encoding: "utf8",
  });
  return output.split("\0").filter(Boolean).sort((left, right) => left.localeCompare(right));
}

function isExcluded(relativePath) {
  return relativePath.split("/").some((part) => EXCLUDED_PATH_PARTS.has(part));
}

function isDocumentationSource(relativePath) {
  if (isExcluded(relativePath)) {
    return false;
  }

  const extension = path.posix.extname(relativePath).toLowerCase();
  if (DOCUMENT_EXTENSIONS.has(extension)) {
    return true;
  }

  if (extension) {
    return false;
  }

  return EXTENSIONLESS_DOCUMENT_NAMES.has(path.posix.basename(relativePath).toLowerCase());
}

function companionPath(sourcePath) {
  const extension = path.posix.extname(sourcePath);
  return extension ? `${sourcePath.slice(0, -extension.length)}.html` : `${sourcePath}.html`;
}

function documentTitle(source, sourcePath) {
  const heading = source.match(/^#\s+(.+?)\s*$/m)?.[1];
  if (heading) {
    return heading
      .replace(/!\[([^\]]*)\]\([^)]*\)/g, "$1")
      .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
      .replace(/[*_~`]/g, "")
      .trim();
  }

  const basename = path.posix.basename(sourcePath, path.posix.extname(sourcePath));
  return basename.replaceAll(/[-_]+/g, " ").replaceAll(/\s+/g, " ").trim() || "Documentation";
}

function renderBody(source, sourcePath) {
  const extension = path.posix.extname(sourcePath).toLowerCase();
  if (FORMAT_AWARE_RENDERER_REQUIRED.has(extension)) {
    throw new Error(
      `${sourcePath} requires a format-aware ${extension} renderer before HTML parity can be generated`
    );
  }

  if (extension === ".md") {
    return marked.parse(source);
  }

  if (!source) {
    return "";
  }

  return `<pre class="plain-document">${escapeHtml(source)}</pre>\n`;
}

function renderDocument(source, sourcePath) {
  const title = documentTitle(source, sourcePath);
  const body = renderBody(source, sourcePath);
  const commentSafeSourcePath = escapeHtml(sourcePath).replaceAll("--", "&#45;&#45;");
  return `<!doctype html>
<!-- Generated by scripts/generate-docs.mjs from ${commentSafeSourcePath}. Do not edit directly. -->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(title)}</title>
  <style>
    :root { color-scheme: light dark; font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }
    body { margin: 0; color: CanvasText; background: Canvas; line-height: 1.6; }
    .skip-link { position: absolute; left: 1rem; top: -5rem; padding: 0.5rem 0.75rem; background: Canvas; border: 1px solid; z-index: 1; }
    .skip-link:focus { top: 1rem; }
    main { width: min(72rem, calc(100% - 2rem)); margin: 0 auto; padding: 2rem 0 4rem; }
    h1, h2, h3, h4, h5, h6 { line-height: 1.25; }
    a { color: LinkText; }
    img { max-width: 100%; height: auto; }
    pre, code, kbd, samp { font-family: ui-monospace, SFMono-Regular, Consolas, "Liberation Mono", monospace; }
    code { overflow-wrap: anywhere; }
    pre { overflow-x: auto; padding: 1rem; border: 1px solid color-mix(in srgb, CanvasText 25%, transparent); border-radius: 0.4rem; }
    pre code { overflow-wrap: normal; }
    blockquote { margin-left: 0; padding-left: 1rem; border-left: 0.25rem solid color-mix(in srgb, CanvasText 35%, transparent); }
    table { width: 100%; border-collapse: collapse; }
    th, td { padding: 0.45rem 0.65rem; border: 1px solid color-mix(in srgb, CanvasText 25%, transparent); text-align: left; vertical-align: top; }
    .plain-document { white-space: pre-wrap; }
  </style>
</head>
<body>
  <a class="skip-link" href="#document">Skip to content</a>
  <main id="document" aria-label="${escapeHtml(title)}">
${body}  </main>
</body>
</html>
`;
}

async function expectedDocuments(files) {
  const sources = files.filter(isDocumentationSource);
  const outputs = new Map();

  for (const sourcePath of sources) {
    const outputPath = companionPath(sourcePath);
    if (outputs.has(outputPath)) {
      throw new Error(
        `Documentation sources ${outputs.get(outputPath).sourcePath} and ${sourcePath} share ${outputPath}`
      );
    }

    const source = await readFile(path.join(REPO_ROOT, sourcePath), "utf8");
    outputs.set(outputPath, {
      sourcePath,
      content: renderDocument(source, sourcePath),
    });
  }

  return outputs;
}

async function generatedHtmlFiles(files) {
  const generated = [];
  for (const relativePath of files.filter((file) => file.toLowerCase().endsWith(".html"))) {
    const content = await readFile(path.join(REPO_ROOT, relativePath), "utf8");
    if (content.startsWith(`<!doctype html>\n${GENERATED_PREFIX}`)) {
      generated.push(relativePath);
    }
  }
  return generated;
}

function isGeneratedDocument(content) {
  return content.startsWith(`<!doctype html>\n${GENERATED_PREFIX}`);
}

async function writeDocuments(files, expected) {
  let changed = 0;
  for (const [outputPath, { sourcePath, content }] of expected) {
    const absolutePath = path.join(REPO_ROOT, outputPath);
    let current = null;
    try {
      current = await readFile(absolutePath, "utf8");
    } catch (error) {
      if (error.code !== "ENOENT") {
        throw error;
      }
    }

    if (current !== null && !isGeneratedDocument(current)) {
      throw new Error(
        `Refusing to overwrite non-generated HTML companion ${outputPath} for ${sourcePath}`
      );
    }

    if (current !== content) {
      await writeFile(absolutePath, content, "utf8");
      changed += 1;
      console.log(`Rendered ${outputPath}`);
    }
  }

  for (const orphanPath of await generatedHtmlFiles(files)) {
    if (!expected.has(orphanPath)) {
      await rm(path.join(REPO_ROOT, orphanPath));
      changed += 1;
      console.log(`Removed orphaned ${orphanPath}`);
    }
  }

  console.log(
    `Documentation HTML generation complete: ${expected.size} source file(s), ${changed} change(s).`
  );
}

async function checkDocuments(files, expected) {
  const problems = [];
  for (const [outputPath, { sourcePath, content }] of expected) {
    try {
      const current = await readFile(path.join(REPO_ROOT, outputPath), "utf8");
      if (!isGeneratedDocument(current)) {
        problems.push(`${outputPath} exists but is not owned by the documentation generator`);
      } else if (current !== content) {
        problems.push(`${outputPath} is stale relative to ${sourcePath}`);
      }
    } catch (error) {
      if (error.code === "ENOENT") {
        problems.push(`${outputPath} is missing for ${sourcePath}`);
      } else {
        throw error;
      }
    }
  }

  for (const orphanPath of await generatedHtmlFiles(files)) {
    if (!expected.has(orphanPath)) {
      problems.push(`${orphanPath} is generated but its source is missing`);
    }
  }

  if (problems.length > 0) {
    console.error("Documentation HTML parity check failed:");
    for (const problem of problems) {
      console.error(`- ${problem}`);
    }
    console.error("Run `npm run docs:generate` and commit the resulting HTML companions.");
    process.exitCode = 1;
    return;
  }

  console.log(`Documentation HTML parity verified for ${expected.size} source file(s).`);
}

async function main() {
  const mode = process.argv[2];
  if (mode !== "--write" && mode !== "--check") {
    throw new Error("Usage: node scripts/generate-docs.mjs --write|--check");
  }

  const files = repositoryFiles();
  const expected = await expectedDocuments(files);
  if (mode === "--write") {
    await writeDocuments(files, expected);
  } else {
    await checkDocuments(files, expected);
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
